//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UiResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UiTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UiResources.UiTexts", typeof(UiTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Information.
        /// </summary>
        public static string account_information {
            get {
                return ResourceManager.GetString("account_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Become a member.
        /// </summary>
        public static string become_a_member {
            get {
                return ResourceManager.GetString("become_a_member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string email_address {
            get {
                return ResourceManager.GetString("email_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string enter {
            get {
                return ResourceManager.GetString("enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email belongs to a registered member already. If it&apos;s yours and you forgot your password please visit recovery page. If there&apos;s any problem logging in please contact us. You&apos;ll find contact information at the bottom of the page..
        /// </summary>
        public static string error_already_a_user {
            get {
                return ResourceManager.GetString("error_already_a_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password provided is incorrect..
        /// </summary>
        public static string error_authentication_failed {
            get {
                return ResourceManager.GetString("error_authentication_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mistype? Email address is incorrect. Please review it and then retry..
        /// </summary>
        public static string error_email {
            get {
                return ResourceManager.GetString("error_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! Unfortunately wesite can&apos;t respond to requests temporarily. This problem will be fixed soon. Please retry in a few minutes. Sorry for the inconvinience..
        /// </summary>
        public static string error_internal {
            get {
                return ResourceManager.GetString("error_internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a security issue with data you provided. Probably a typing mistake. Please retry..
        /// </summary>
        public static string error_security {
            get {
                return ResourceManager.GetString("error_security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password.
        /// </summary>
        public static string forgot_your_password {
            get {
                return ResourceManager.GetString("forgot_your_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has.
        /// </summary>
        public static string has {
            get {
                return ResourceManager.GetString("has", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has NOT.
        /// </summary>
        public static string has_not {
            get {
                return ResourceManager.GetString("has_not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Off.
        /// </summary>
        public static string log_off {
            get {
                return ResourceManager.GetString("log_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log On.
        /// </summary>
        public static string log_on {
            get {
                return ResourceManager.GetString("log_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ltr.
        /// </summary>
        public static string page_direction {
            get {
                return ResourceManager.GetString("page_direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page number.
        /// </summary>
        public static string page_number {
            get {
                return ResourceManager.GetString("page_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password recovery wizard.
        /// </summary>
        public static string password_recovery_wizard {
            get {
                return ResourceManager.GetString("password_recovery_wizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فارسی.
        /// </summary>
        public static string persian {
            get {
                return ResourceManager.GetString("persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string product_name {
            get {
                return ResourceManager.GetString("product_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string product_price {
            get {
                return ResourceManager.GetString("product_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Releaseed at.
        /// </summary>
        public static string product_release_date {
            get {
                return ResourceManager.GetString("product_release_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string product_version {
            get {
                return ResourceManager.GetString("product_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Me!.
        /// </summary>
        public static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration form.
        /// </summary>
        public static string registeration_form {
            get {
                return ResourceManager.GetString("registeration_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Information.
        /// </summary>
        public static string registration_information {
            get {
                return ResourceManager.GetString("registration_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RememberMe.
        /// </summary>
        public static string remember_me {
            get {
                return ResourceManager.GetString("remember_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support multiple languages.
        /// </summary>
        public static string support_multiple_languages {
            get {
                return ResourceManager.GetString("support_multiple_languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        public static string user_name {
            get {
                return ResourceManager.GetString("user_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
    }
}
