//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UiResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UiTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UiResources.UiTexts", typeof(UiTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Information.
        /// </summary>
        public static string account_information {
            get {
                return ResourceManager.GetString("account_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately it was not possible to save changes. Please try again later..
        /// </summary>
        public static string alert_save_failed {
            get {
                return ResourceManager.GetString("alert_save_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes saved successfully..
        /// </summary>
        public static string alert_save_ok {
            get {
                return ResourceManager.GetString("alert_save_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Announcement.
        /// </summary>
        public static string announcements {
            get {
                return ResourceManager.GetString("announcements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest.
        /// </summary>
        public static string anonymous {
            get {
                return ResourceManager.GetString("anonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website language.
        /// </summary>
        public static string app_culture {
            get {
                return ResourceManager.GetString("app_culture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Persian Softwares.
        /// </summary>
        public static string app_title {
            get {
                return ResourceManager.GetString("app_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Become a member.
        /// </summary>
        public static string become_a_member {
            get {
                return ResourceManager.GetString("become_a_member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Softwares.
        /// </summary>
        public static string best_softwares {
            get {
                return ResourceManager.GetString("best_softwares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branches.
        /// </summary>
        public static string branches {
            get {
                return ResourceManager.GetString("branches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot edit a message that you didn&apos;t create.
        /// </summary>
        public static string cant_edit_somone_else_message {
            get {
                return ResourceManager.GetString("cant_edit_somone_else_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,.
        /// </summary>
        public static string comma {
            get {
                return ResourceManager.GetString("comma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm operation.
        /// </summary>
        public static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to delete a discussion message. If message has replies attached to it, only content will be removed. Are you sure you want to remove this message?.
        /// </summary>
        public static string confirm_discussion_delete {
            get {
                return ResourceManager.GetString("confirm_discussion_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to report this message as inappropriate or abuse. If a message is reported as abuse multiple times by users then it will be deleted automatically. Yet moderators will check such messages as soon as they can. Are you sure you want to report this message as inappropriate?.
        /// </summary>
        public static string confirm_discussion_report {
            get {
                return ResourceManager.GetString("confirm_discussion_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact site admin.
        /// </summary>
        public static string contact_admin {
            get {
                return ResourceManager.GetString("contact_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string contact_media {
            get {
                return ResourceManager.GetString("contact_media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string contact_name {
            get {
                return ResourceManager.GetString("contact_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string contact_title {
            get {
                return ResourceManager.GetString("contact_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string contact_value {
            get {
                return ResourceManager.GetString("contact_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete message.
        /// </summary>
        public static string delete_message {
            get {
                return ResourceManager.GetString("delete_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discuss.
        /// </summary>
        public static string discuss {
            get {
                return ResourceManager.GetString("discuss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name/alias (Will be visible by all users).
        /// </summary>
        public static string display_name {
            get {
                return ResourceManager.GetString("display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download demo(All Available languages).
        /// </summary>
        public static string download_common_demo {
            get {
                return ResourceManager.GetString("download_common_demo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download demo (Selected language).
        /// </summary>
        public static string download_local_demo {
            get {
                return ResourceManager.GetString("download_local_demo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string edit_message {
            get {
                return ResourceManager.GetString("edit_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string email_address {
            get {
                return ResourceManager.GetString("email_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string enter {
            get {
                return ResourceManager.GetString("enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email belongs to a registered member already. If it&apos;s yours and you forgot your password please visit recovery page. If there&apos;s any problem logging in please contact us. You&apos;ll find contact information at the bottom of the page..
        /// </summary>
        public static string error_already_a_user {
            get {
                return ResourceManager.GetString("error_already_a_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password provided is incorrect..
        /// </summary>
        public static string error_authentication_failed {
            get {
                return ResourceManager.GetString("error_authentication_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dangerous input detected.
        /// </summary>
        public static string error_bad_input {
            get {
                return ResourceManager.GetString("error_bad_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mistype? Email address is incorrect. Please review it and then retry..
        /// </summary>
        public static string error_email {
            get {
                return ResourceManager.GetString("error_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! Unfortunately wesite can&apos;t respond to requests temporarily. This problem will be fixed soon. Please retry in a few minutes. Sorry for the inconvinience..
        /// </summary>
        public static string error_internal {
            get {
                return ResourceManager.GetString("error_internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a security issue with data you provided. Probably a typing mistake. Please retry..
        /// </summary>
        public static string error_security {
            get {
                return ResourceManager.GetString("error_security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excellent.
        /// </summary>
        public static string excellent_product {
            get {
                return ResourceManager.GetString("excellent_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra services.
        /// </summary>
        public static string extra_services {
            get {
                return ResourceManager.GetString("extra_services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest blog entries.
        /// </summary>
        public static string featured_blog_entries {
            get {
                return ResourceManager.GetString("featured_blog_entries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured Products.
        /// </summary>
        public static string featured_products {
            get {
                return ResourceManager.GetString("featured_products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size: .
        /// </summary>
        public static string file_size {
            get {
                return ResourceManager.GetString("file_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left.
        /// </summary>
        public static string float_left {
            get {
                return ResourceManager.GetString("float_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to right.
        /// </summary>
        public static string float_right {
            get {
                return ResourceManager.GetString("float_right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password.
        /// </summary>
        public static string forgot_your_password {
            get {
                return ResourceManager.GetString("forgot_your_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has.
        /// </summary>
        public static string has {
            get {
                return ResourceManager.GetString("has", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has NOT.
        /// </summary>
        public static string has_not {
            get {
                return ResourceManager.GetString("has_not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to return to {0} product catalog.
        /// </summary>
        public static string inf_return_to_catalog {
            get {
                return ResourceManager.GetString("inf_return_to_catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To see more screenshots thumbnails scroll down. To enlarge a thumbnail click on it..
        /// </summary>
        public static string inf_screenshot_thumbs {
            get {
                return ResourceManager.GetString("inf_screenshot_thumbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found &lt;b&gt;{0}&lt;/b&gt; softwares in this category.
        /// </summary>
        public static string items_found {
            get {
                return ResourceManager.GetString("items_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal details.
        /// </summary>
        public static string legal_details {
            get {
                return ResourceManager.GetString("legal_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Off.
        /// </summary>
        public static string log_off {
            get {
                return ResourceManager.GetString("log_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log On.
        /// </summary>
        public static string log_on {
            get {
                return ResourceManager.GetString("log_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to be a member of the site and log in to site to download demos.
        /// </summary>
        public static string login_to_download_demo {
            get {
                return ResourceManager.GetString("login_to_download_demo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to be a member of the site and log in to site to post a message or edit your messages..
        /// </summary>
        public static string login_to_manage_comments {
            get {
                return ResourceManager.GetString("login_to_manage_comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to vote for this product you need to be logged in to the system.
        /// </summary>
        public static string login_to_vote {
            get {
                return ResourceManager.GetString("login_to_vote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megabytes.
        /// </summary>
        public static string megabytes {
            get {
                return ResourceManager.GetString("megabytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member since: .
        /// </summary>
        public static string member_since {
            get {
                return ResourceManager.GetString("member_since", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        public static string members {
            get {
                return ResourceManager.GetString("members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        public static string message_body {
            get {
                return ResourceManager.GetString("message_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Details.
        /// </summary>
        public static string message_details {
            get {
                return ResourceManager.GetString("message_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In response to this message: .
        /// </summary>
        public static string message_original {
            get {
                return ResourceManager.GetString("message_original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send message.
        /// </summary>
        public static string message_send {
            get {
                return ResourceManager.GetString("message_send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string message_subject {
            get {
                return ResourceManager.GetString("message_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        public static string message_type_answer {
            get {
                return ResourceManager.GetString("message_type_answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string message_type_general {
            get {
                return ResourceManager.GetString("message_type_general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joke.
        /// </summary>
        public static string message_type_joke {
            get {
                return ResourceManager.GetString("message_type_joke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string message_type_question {
            get {
                return ResourceManager.GetString("message_type_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See more details of this product.
        /// </summary>
        public static string more_details {
            get {
                return ResourceManager.GetString("more_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to see more screenshots.
        /// </summary>
        public static string more_images {
            get {
                return ResourceManager.GetString("more_images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My profile.
        /// </summary>
        public static string my_profile {
            get {
                return ResourceManager.GetString("my_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string my_settings {
            get {
                return ResourceManager.GetString("my_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discuss this product.
        /// </summary>
        public static string new_discussion {
            get {
                return ResourceManager.GetString("new_discussion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This product does not have a demo available to download.
        /// </summary>
        public static string no_demo_available {
            get {
                return ResourceManager.GetString("no_demo_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not defined.
        /// </summary>
        public static string not_defined {
            get {
                return ResourceManager.GetString("not_defined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing special.
        /// </summary>
        public static string nothing_special {
            get {
                return ResourceManager.GetString("nothing_special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Of.
        /// </summary>
        public static string of {
            get {
                return ResourceManager.GetString("of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string overview {
            get {
                return ResourceManager.GetString("overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorted in &lt;b&gt;{0}&lt;/b&gt; pages.
        /// </summary>
        public static string page_count {
            get {
                return ResourceManager.GetString("page_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ltr.
        /// </summary>
        public static string page_direction {
            get {
                return ResourceManager.GetString("page_direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page doesn&apos;t exists.
        /// </summary>
        public static string page_not_found {
            get {
                return ResourceManager.GetString("page_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately the page you are looking for does not exist on our website. Either entered URL is incorrect or the page had been removed..
        /// </summary>
        public static string page_not_found_content {
            get {
                return ResourceManager.GetString("page_not_found_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page number.
        /// </summary>
        public static string page_number {
            get {
                return ResourceManager.GetString("page_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password recovery wizard.
        /// </summary>
        public static string password_recovery_wizard {
            get {
                return ResourceManager.GetString("password_recovery_wizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فارسی.
        /// </summary>
        public static string persian {
            get {
                return ResourceManager.GetString("persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad.
        /// </summary>
        public static string poor_product {
            get {
                return ResourceManager.GetString("poor_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular Products.
        /// </summary>
        public static string popular_products {
            get {
                return ResourceManager.GetString("popular_products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string print {
            get {
                return ResourceManager.GetString("print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producer comments.
        /// </summary>
        public static string producer_comments {
            get {
                return ResourceManager.GetString("producer_comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to access.
        /// </summary>
        public static string product_access {
            get {
                return ResourceManager.GetString("product_access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        public static string product_backup {
            get {
                return ResourceManager.GetString("product_backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction.
        /// </summary>
        public static string product_brief_description {
            get {
                return ResourceManager.GetString("product_brief_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string product_contacts {
            get {
                return ResourceManager.GetString("product_contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customization.
        /// </summary>
        public static string product_customization {
            get {
                return ResourceManager.GetString("product_customization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo.
        /// </summary>
        public static string product_demo {
            get {
                return ResourceManager.GetString("product_demo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment.
        /// </summary>
        public static string product_environment {
            get {
                return ResourceManager.GetString("product_environment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extendability.
        /// </summary>
        public static string product_extendabilities {
            get {
                return ResourceManager.GetString("product_extendabilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guaranty.
        /// </summary>
        public static string product_guaranty {
            get {
                return ResourceManager.GetString("product_guaranty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware requirements.
        /// </summary>
        public static string product_hardware_requirements {
            get {
                return ResourceManager.GetString("product_hardware_requirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation.
        /// </summary>
        public static string product_installation {
            get {
                return ResourceManager.GetString("product_installation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string product_language {
            get {
                return ResourceManager.GetString("product_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language extendability.
        /// </summary>
        public static string product_language_extendable {
            get {
                return ResourceManager.GetString("product_language_extendable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported languages.
        /// </summary>
        public static string product_languages {
            get {
                return ResourceManager.GetString("product_languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ability to add new language.
        /// </summary>
        public static string product_languages_extendablity {
            get {
                return ResourceManager.GetString("product_languages_extendablity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editors rating.
        /// </summary>
        public static string product_list_editor_rating {
            get {
                return ResourceManager.GetString("product_list_editor_rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        public static string product_list_sort_features {
            get {
                return ResourceManager.GetString("product_list_sort_features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name(A-Z).
        /// </summary>
        public static string product_list_sort_name {
            get {
                return ResourceManager.GetString("product_list_sort_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name(Z-A).
        /// </summary>
        public static string product_list_sort_name_desc {
            get {
                return ResourceManager.GetString("product_list_sort_name_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order(sort) list by:.
        /// </summary>
        public static string product_list_sort_order_caption {
            get {
                return ResourceManager.GetString("product_list_sort_order_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popularity.
        /// </summary>
        public static string product_list_sort_popularity {
            get {
                return ResourceManager.GetString("product_list_sort_popularity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price(Lower first).
        /// </summary>
        public static string product_list_sort_price {
            get {
                return ResourceManager.GetString("product_list_sort_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price(Higher first).
        /// </summary>
        public static string product_list_sort_price_desc {
            get {
                return ResourceManager.GetString("product_list_sort_price_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReleaseDate(Older first).
        /// </summary>
        public static string product_list_sort_release {
            get {
                return ResourceManager.GetString("product_list_sort_release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReleaseDate(Younger first).
        /// </summary>
        public static string product_list_sort_release_desc {
            get {
                return ResourceManager.GetString("product_list_sort_release_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users ratings.
        /// </summary>
        public static string product_list_user_rating {
            get {
                return ResourceManager.GetString("product_list_user_rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string product_name {
            get {
                return ResourceManager.GetString("product_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network capabilities.
        /// </summary>
        public static string product_network {
            get {
                return ResourceManager.GetString("product_network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string product_payment {
            get {
                return ResourceManager.GetString("product_payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string product_price {
            get {
                return ResourceManager.GetString("product_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price details.
        /// </summary>
        public static string product_price_details {
            get {
                return ResourceManager.GetString("product_price_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Releaseed at.
        /// </summary>
        public static string product_release_date {
            get {
                return ResourceManager.GetString("product_release_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported operating systems.
        /// </summary>
        public static string product_software_platform {
            get {
                return ResourceManager.GetString("product_software_platform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software requirements.
        /// </summary>
        public static string product_software_requirements {
            get {
                return ResourceManager.GetString("product_software_requirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source code.
        /// </summary>
        public static string product_source {
            get {
                return ResourceManager.GetString("product_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string product_support {
            get {
                return ResourceManager.GetString("product_support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support methods.
        /// </summary>
        public static string product_support_access {
            get {
                return ResourceManager.GetString("product_support_access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training.
        /// </summary>
        public static string product_training {
            get {
                return ResourceManager.GetString("product_training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string product_update {
            get {
                return ResourceManager.GetString("product_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string product_version {
            get {
                return ResourceManager.GetString("product_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume size.
        /// </summary>
        public static string product_volume_size {
            get {
                return ResourceManager.GetString("product_volume_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to read more about this.
        /// </summary>
        public static string read_more {
            get {
                return ResourceManager.GetString("read_more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Me!.
        /// </summary>
        public static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration form.
        /// </summary>
        public static string registeration_form {
            get {
                return ResourceManager.GetString("registeration_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered products.
        /// </summary>
        public static string registered_products {
            get {
                return ResourceManager.GetString("registered_products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Information.
        /// </summary>
        public static string registration_information {
            get {
                return ResourceManager.GetString("registration_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Tags.
        /// </summary>
        public static string related_tags {
            get {
                return ResourceManager.GetString("related_tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RememberMe.
        /// </summary>
        public static string remember_me {
            get {
                return ResourceManager.GetString("remember_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply.
        /// </summary>
        public static string reply {
            get {
                return ResourceManager.GetString("reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report to remove this mesage.
        /// </summary>
        public static string report_abuse {
            get {
                return ResourceManager.GetString("report_abuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshots.
        /// </summary>
        public static string screenshots {
            get {
                return ResourceManager.GetString("screenshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security restriction.
        /// </summary>
        public static string security_error {
            get {
                return ResourceManager.GetString("security_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action terminated. What you wanted to do is restricted by security administrators. If there&apos;s a problem please inform us about it. Thank you..
        /// </summary>
        public static string security_error_content {
            get {
                return ResourceManager.GetString("security_error_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings help you modify the page the way you like it. When you made changes please press save button otherwise your changes will be lost..
        /// </summary>
        public static string settings_brief {
            get {
                return ResourceManager.GetString("settings_brief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Categories.
        /// </summary>
        public static string software_categories {
            get {
                return ResourceManager.GetString("software_categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly Intro.
        /// </summary>
        public static string software_school {
            get {
                return ResourceManager.GetString("software_school", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support for multiple languages.
        /// </summary>
        public static string support_multiple_languages {
            get {
                return ResourceManager.GetString("support_multiple_languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical details.
        /// </summary>
        public static string technical_details {
            get {
                return ResourceManager.GetString("technical_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Catalog.
        /// </summary>
        public static string title_catalog {
            get {
                return ResourceManager.GetString("title_catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit message.
        /// </summary>
        public static string title_discussion_edit {
            get {
                return ResourceManager.GetString("title_discussion_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string title_error {
            get {
                return ResourceManager.GetString("title_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string title_index {
            get {
                return ResourceManager.GetString("title_index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of products.
        /// </summary>
        public static string title_list {
            get {
                return ResourceManager.GetString("title_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Not Found.
        /// </summary>
        public static string title_not_found {
            get {
                return ResourceManager.GetString("title_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User profile.
        /// </summary>
        public static string title_profile {
            get {
                return ResourceManager.GetString("title_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product screenshots.
        /// </summary>
        public static string title_screenshots {
            get {
                return ResourceManager.GetString("title_screenshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Settings.
        /// </summary>
        public static string title_settings {
            get {
                return ResourceManager.GetString("title_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occured.
        /// </summary>
        public static string unknown_error {
            get {
                return ResourceManager.GetString("unknown_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error prevented website to function properly. We are sorry for the inconvenience. Please try again later..
        /// </summary>
        public static string unknown_error_content {
            get {
                return ResourceManager.GetString("unknown_error_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        public static string user_name {
            get {
                return ResourceManager.GetString("user_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Number.
        /// </summary>
        public static string version_number {
            get {
                return ResourceManager.GetString("version_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        public static string views {
            get {
                return ResourceManager.GetString("views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote.
        /// </summary>
        public static string vote {
            get {
                return ResourceManager.GetString("vote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votes.
        /// </summary>
        public static string votes {
            get {
                return ResourceManager.GetString("votes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string website {
            get {
                return ResourceManager.GetString("website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already voted {0} out of 5 for this product.
        /// </summary>
        public static string your_vote {
            get {
                return ResourceManager.GetString("your_vote", resourceCulture);
            }
        }
    }
}
